// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZdeo2tsNTJhMXINsnXtI8CC5ApfIX--o',
    appId: '1:957390818409:web:bd9464a6f9d08dc9d6a6f8',
    messagingSenderId: '957390818409',
    projectId: 'lumiere-velas',
    authDomain: 'lumiere-velas.firebaseapp.com',
    storageBucket: 'lumiere-velas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd5Nfi-w637MeFAS1llIMzM2uM3_aZz88',
    appId: '1:957390818409:android:27ab8740df12db45d6a6f8',
    messagingSenderId: '957390818409',
    projectId: 'lumiere-velas',
    storageBucket: 'lumiere-velas.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlWWNMx4PjieYU8y7p1TT3Sx4QO4-x8o8',
    appId: '1:957390818409:ios:614057c3351f9560d6a6f8',
    messagingSenderId: '957390818409',
    projectId: 'lumiere-velas',
    storageBucket: 'lumiere-velas.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlWWNMx4PjieYU8y7p1TT3Sx4QO4-x8o8',
    appId: '1:957390818409:ios:614057c3351f9560d6a6f8',
    messagingSenderId: '957390818409',
    projectId: 'lumiere-velas',
    storageBucket: 'lumiere-velas.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZdeo2tsNTJhMXINsnXtI8CC5ApfIX--o',
    appId: '1:957390818409:web:91b1f956c123d66cd6a6f8',
    messagingSenderId: '957390818409',
    projectId: 'lumiere-velas',
    authDomain: 'lumiere-velas.firebaseapp.com',
    storageBucket: 'lumiere-velas.firebasestorage.app',
  );
}
